services:
  - type: web
    name: wppconnect-server
    env: docker
    plan: free
    autoDeploy: true

    envVars:
      - key: SECRET_KEY
        generateValue: true

      - key: PORT
        value: 21465

      - key: HOST
        value: 0.0.0.0

      - key: HEADLESS
        value: true

      - key: LOG_LEVEL
        value: silly

      - key: WEBHOOK_URL
        value: ""

      - key: WEBHOOK_BY_EVENTS
        value: false

      - key: SESSION_NAME
        value: main

      - key: CHROME_ARGS
        value: --no-sandbox,--disable-setuid-sandbox

disks:
  - name: wpp-data
    mountPath: /usr/src/wpp-server/tokens
    sizeGB: 1
